[icons]
icons = "awesome6"

[theme]
theme = "plain"
[theme.overrides]
separator = ""

[[block]]
block = "privacy"
[[block.driver]]
name = "pipewire"
exclude_input = ["PulseAudio Volume Control"]

[[block]]
block = "music"
format = " {$icon $combo.str(max_w:25)|} "
[[block.click]]
button = "left"
action = "play_pause"

[[block]]
block = "bluetooth"
mac = "E0:0A:F6:CB:89:A2"
disconnected_format = ""

[[block]]
block = "net"
format = "$signal_strength $icon $ssid "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
format = " $icon $barchart $utilization "

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "

[[block]]
block = "battery"
"interval" = 5
format = " $icon $percentage "
full_format = " $icon $percentage "
empty_format = " $icon $percentage "

[[block]]
block = "sound"
headphones_indicator = true
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "backlight"

[[block]]
block = "time"
format = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %H:%M') "
